config/routes.rb
Rails.application.routes.draw do

    resources :authentications

  resources :recipes do
	  resources :comments
	end

  root to: 'visitors#index'


  get 'tags/:tag', to: 'recipes#index', as: :tag
   get '/auth/:provider/callback' => 'authentications#create'
   delete '/authentications"' => 'authentications#destroy'
   devise_for :users, :controllers => {:registrations => "registrations"}
   
  resources :users

   mount Ckeditor::Engine => '/ckeditor'
   
   get '/autocomplete' => 'visitors#autocomplete'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :user
	belongs_to :recipe
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def create
    @post = Recipe.find(params[:recipe_id])
    @comment = @post.comments.create(params[:comment].permit(:content))
    @comment.commenter= current_user.name
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to root_path }
      end
    end
  end
  
def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.slim
= form_for @comment do |f|
  - if @comment.errors.any?
    #error_explanation
      h2 = "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      ul
        - @comment.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :content
    = f.text_field :content
  .field
    = f.label :commenter
    = f.text_field :commenter
  .field
    = f.label :references
    = f.text_field :references
  .field
    = f.label :references
    = f.text_field :references
  .actions = f.submit

app/views/comments/edit.html.slim
h1 Editing comment

== render 'form'

= link_to 'Show', @comment
'|
= link_to 'Back', comments_path

app/views/comments/index.html.slim
h1 Listing comments

table
  thead
    tr
      th Content
      th Commenter
      th References
      th References
      th
      th
      th

  tbody
    - @comments.each do |comment|
      tr
        td = comment.content
        td = comment.commenter
        td = comment.references
        td = comment.references
        td = link_to 'Show', comment
        td = link_to 'Edit', edit_comment_path(comment)
        td = link_to 'Destroy', comment, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.slim
h1 New comment

== render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.slim
p#notice = notice

p
  strong Content:
  = @comment.content
p
  strong Commenter:
  = @comment.commenter
p
  strong References:
  = @comment.references
p
  strong References:
  = @comment.references

= link_to 'Edit', edit_comment_path(@comment)
'|
= link_to 'Back', comments_path