config/routes.rb
Rails.application.routes.draw do

    resources :authentications

  resources :recipes do
	  resources :comments
	end

  root to: 'visitors#index'


  get 'tags/:tag', to: 'recipes#index', as: :tag
   get '/auth/:provider/callback' => 'authentications#create'
   delete '/authentications"' => 'authentications#destroy'
   devise_for :users, :controllers => {:registrations => "registrations"}
   
  resources :users

   mount Ckeditor::Engine => '/ckeditor'
   
   get '/autocomplete' => 'visitors#autocomplete'

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
    def index
        @recipe = Recipe.new
        if params[:query].present?
            @recipes = Recipe.search(params[:query])
            # render :text => @recipes.to_yaml
        else
            @recipes = Recipe.all.reverse
        end
        @tags = Recipe.tag_counts_on(:ingredients)

    end
    def tag_cloud
        @tags = Recipe.tag_counts_on(:ingredients)
    end

    def autocomplete
        render json: Recipe.search(params[:query], autocomplete: true, limit: 10).map(&:name)
    end

end

app/views/visitors/_search.html.slim
= form_tag root_path, class: "form-inline pull-right" , style: "position:relative;top:-60px;", method: :get do
  .input-group.input-group-lg
    - if params[:query].present?
      .input-group-btn
        = link_to "clear", recipes_path, class: "btn btn-default"
    = text_field_tag :query, params[:query], class: "form-control pull-right", id: "recipe_search", autocomplete: "off"
    .input-group-btn
      = submit_tag "Search", class: "btn btn-primary"
br
br

app/views/visitors/_search_ing.html.slim
= form_tag recipes_path, class: "form-inline pull-right" , style: "position:relative;top:-30px;", method: :get do
  .input-group.input-group-lg
    - if params[:tag].present?
      .input-group-btn
        = link_to "clear", recipes_path, class: "btn btn-default"
    = text_field_tag :tag, params[:tag], class: "form-control pull-right", id: "recipe1_search", autocomplete: "off"
    .input-group-btn
      = submit_tag "Search", class: "btn btn-primary"

app/views/visitors/index.html.erb
<%= render 'recipes/recipes' %>

app/views/visitors/index1.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>