config/routes.rb
Rails.application.routes.draw do

    resources :authentications

  resources :recipes do
	  resources :comments
	end

  root to: 'visitors#index'


  get 'tags/:tag', to: 'recipes#index', as: :tag
   get '/auth/:provider/callback' => 'authentications#create'
   delete '/authentications"' => 'authentications#destroy'
   devise_for :users, :controllers => {:registrations => "registrations"}
   
  resources :users

   mount Ckeditor::Engine => '/ckeditor'
   
   get '/autocomplete' => 'visitors#autocomplete'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    searchkick autocomplete: ['name']
    has_and_belongs_to_many :ingredients
    
    has_many :comments

    belongs_to :user

    acts_as_taggable_on :ingredients
    has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :set_recipe, only: [:show, :edit, :update, :destroy]
    before_filter :login_required

    # GET /recipes
    # GET /recipes.json
    def index
        @recipe = Recipe.new
        @tags = Recipe.tag_counts_on(:ingredients)

        if params[:query]
            @recipes = Recipe.search(params[:query])
        else
            if params[:tag]
                @tag = params[:tag].split(',')
                @recipes =Recipe.tagged_with(@tag,:match_all => true).reverse
                if @recipes.count == 0
                    @recipes =Recipe.tagged_with(@tag,:any => true).reverse
                end
            else
                @recipes = Recipe.all.reverse
            end
        end
    end

    # GET /recipes/1
    # GET /recipes/1.json
    def show
    end

    # GET /recipes/new
    def new
        @recipe = Recipe.new
    end

    # GET /recipes/1/edit
    def edit
    end

    # POST /recipes
    # POST /recipes.json
    def create
        @recipe = Recipe.new(recipe_params)
        if current_user
            @recipe.user_id = current_user.id
        end

        respond_to do |format|
            if @recipe.save
                format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
                format.json { render :show, status: :created, location: @recipe }
            else
                format.html { render :new }
                format.json { render json: @recipe.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /recipes/1
    # PATCH/PUT /recipes/1.json
    def update
        respond_to do |format|
            if @recipe.update(recipe_params)
                format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
                format.json { render :show, status: :ok, location: @recipe }
            else
                format.html { render :edit }
                format.json { render json: @recipe.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /recipes/1
    # DELETE /recipes/1.json
    def destroy
        @recipe.destroy
        respond_to do |format|
            format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    def autocomplete
        render json: Recipe.search(params[:query], autocomplete: true, limit: 10).map(&:name)
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
        @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
        params.require(:recipe).permit(:name, :calories, :fat, :protein, :image, :instructions,:ingredient_list)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= simple_form_for(@recipe) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :calories %>
    <%= f.input :fat %>
    <%= f.input :protein %>
    <%= f.input :image %>
  <%= f.input :instructions, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} } %>
  <%= f.input :ingredient_list %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/recipes/_recipes.html.erb
<% if user_signed_in? %>
    <div class="data-box">
    <%= simple_form_for(@recipe) do |f| %>
        <%= f.error_notification %>

    <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :calories %>
        <%= f.input :fat %>
        <%= f.input :protein %>
        <%= f.input :image %>
        <%= f.input :ingredient_list,:label=> "Ingredients(Separate with commas)",:value=>"" %>
    </div>

    <%= f.input :instructions, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} } %>
    <div class="form-actions">
        <%= f.button :submit %>
    </div>

<% end %>
</div>
    </div>
  
    <div class = "popular-box">
<h3> Popular Ingredients </h3>
<div class="tagify"> <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
    <%= link_to tag.name+',',tag_path(tag.name), :class => css_class %>
<% end %> 
</div>
    </div>
<div class = "post-box">
<% @recipes.each do |r| %>
<div class="col-xs-2 postimgimg-responsive ">  <%= image_tag r.user.avatar.url(:medium),:size => "100x100",class: 'postavatar img-c' %> </div>
<div class="col-xs-10">
    <%= link_to "#{image_tag(r.image.url)}".html_safe, r %>
    </div>
<%= raw r.instructions%>
<%= time_ago_in_words r.created_at %>
<br/> Posted by 
<% if current_user.id == r.user_id %>
    <p>You</p>
        <% else %>
    <%= User.find(r.user_id).name %>  
        <% end %>
<hr>
<% r.comments.each do |comment| %>
    <% @user=comment.user%>
<div class="row">
    <div class="col-xs-12 comment">
        <div class="row">
            <div class="col-xs-2 commentimg"> <%= image_tag @user.avatar.url(:medium),:size=>"50x50",class: 'img-thumbnail' %>  </div>
            <div class="col-xs-10">
                <div class="pull-right delete">
                    <% if @user==current_user #|| current_user == r.user%>
                        <%= link_to 'x', [comment.recipe, comment], method: :delete, class: "btn btn-danger btn-xs", title: "Detele Comment", data: { confirm: 'Are you sure?' } %>
                <% end %>
                </div>
                <%= comment.content %><br/>
                <small>-<%= comment.commenter %></small><br/>
            </div>
        </div>
    </div>
</div>  
            <% end %><br>


<%= simple_form_for([r, r.comments.build], :defaults => { :input_html => { :class => "form-control" } } )  do |f| %>
    <%= f.input :content ,{:onfocus => "disable()" , :onblur => "enable()" , :required => true, label: false} %>

<%= f.submit :Comment , {:class => "btn btn-success" , :name => "comment-btn"} %>
            <% end %>



<hr/>
    <% end %>
</div>        
<% else %>
<br><br><br>
<%= render 'search' %>


  <% if @recipes!=nil %>
<% @recipes.each_with_index do |r,i| %>
<div class="b<%=i%2+1%>">
<section class="bussinesscard">
    <div class="flip">
        <div class="front">       
            <div class="top">       
                <div class="logo"><%= image_tag(r.image.url) %>
            </div>        
            </div>
            <div class="nametroduction">
                <div class="name"><%= r.name %></div>
                <div class="introduction">Hover to see the nutrition facts</div>
            </div>  
            <div class="contact">           
                <div class="website">
                    <a href="#">Calories :  <%= r.calories %></a>
                </div>
                <div class="twitter">
                    <a href="#">Fat : <%= r.fat %></a> 
                </div>                        
                <div class="email ">
                    <a href="#">Protein :  <%= r.protein %></a>
                </div>
                <div class="procedure">
                    <%= link_to "Procedure",r , :class => 'styled-button-10' %>
                </div>
            </div>            
        </div>
        <div class="back"></div> 
    </div>
</section>
    </div>

    <% end %>
    <% end %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<%= render 'recipes' %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<div class="tablify">
<table class="table table-hover">
    <tbody>
    <tr>
        <p>
        <td> <strong>Name:</strong> </td>
        <td>  <%= @recipe.name %> </td>
        </p>
    </tr> 
    <tr>
        <p>
        <td> <strong>Calories:</strong></td>
        <td>  <%= @recipe.calories %></td>
        </p>
    </tr>
    <tr>
        <p>
        <td> <strong>Fat:</strong></td>
        <td><%= @recipe.fat %></td>
        </p>
    </tr>
    <tr>
        <p>
        <td> <strong>Protein:</strong></td>
        <td> <%= @recipe.protein %></td>
        </p>
    </tr>
    <tr>

    <p>
    <td><strong> Ingredients:</strong>
    </td>   <td>    <%= raw @recipe.ingredients.map { |t| link_to t, tag_path(t) }.join(', ') %>
</td>
        </p>
    </tr>
    </tbody>
</table> </div>
<div class="row">
<div class="recipe-no-img">
    <%= image_tag @recipe.image.url %>
</div>
</div>
</div>
<div class="row" style="position:relative; top:350px; background:white; left:20px; width:80%; margin:auto;">
    <%= raw @recipe.instructions %>
</div>
<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>