config/routes.rb
Rails.application.routes.draw do

    resources :authentications

  resources :recipes do
	  resources :comments
	end

  root to: 'visitors#index'


  get 'tags/:tag', to: 'recipes#index', as: :tag
   get '/auth/:provider/callback' => 'authentications#create'
   delete '/authentications"' => 'authentications#destroy'
   devise_for :users, :controllers => {:registrations => "registrations"}
   
  resources :users

   mount Ckeditor::Engine => '/ckeditor'
   
   get '/autocomplete' => 'visitors#autocomplete'

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  before_action :set_authentication, only: [:show, :edit, :update, :destroy]

  # GET /authentications
  # GET /authentications.json
  def index
    if current_user
      @authentications = current_user.authentications
    else
  flash[:notice]='Please login first'
  redirect_to root_path
    end
  end

  # GET /authentications/1
  # GET /authentications/1.json
  def show
  end

  # GET /authentications/new
  def new
    @authentication = Authentication.new
  end

  # GET /authentications/1/edit
  def edit
  end


  # POST /authentications
  # POST /authentications.json
  def create
  redir = false
  #render :text => request.env["omniauth.auth"].to_yaml
  omniauth = request.env["omniauth.auth"]
  if omniauth['provider']=='facebook'
  session[:fb_token]=omniauth.credentials.token
  end
  authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
  #render :text => omniauth.to_json
  if authentication
    flash[:notice] = "Signed in successfully using existing authentication."
  #@graph = Koala::Facebook::API.new(omniauth.credentials.token, GRAPH_SECRET)
          #profile = @graph.get_object("me")
      #friends = @graph.get_connections("me", "feed")
        #render :text => friends.to_yaml
        #render :partial => 'home/fb.html.erb', :locals => { :posts_streams => friends }
    #@graph.put_connections("me", "feed", :message => "I am writing on my wall!")

    # Three-part queries are easy too!
    #@graph.get_connections("me", "mutualfriends/#{friend_id}")

    # You can use the Timeline API:
    # (see https://developers.facebook.com/docs/beta/opengraph/tutorial/)
    #@graph.put_connections("me", "namespace:action", :object => object_url)

    sign_in_and_redirect(:user, authentication.user)
  elsif current_user
    current_user.authentications.create!(:provider => omniauth['provider'], :uid => omniauth['uid'])
    flash[:notice] = "Authentication successful."
    image_set(current_user,omniauth)
    update_omniauth(current_user,omniauth)
    redirect_to authentications_url
  else
    user = User.find_by_email(omniauth['info']['email'])
    if user
      flash[:notice] = "Signed in and added authentication successfully."
      user.authentications.create!(:provider => omniauth['provider'], :uid => omniauth['uid'])
      image_set(user,omniauth)
      update_omniauth(user,omniauth)
      sign_in_and_redirect(:user, user)
    else
      user=User.new
      redir=true
    end
    user.apply_omniauth(omniauth)
    # user.skip_confirmation!
    image_set(user,omniauth)
    if user.save && redir
      flash[:notice] = "Signed in successfully."
      sign_in_and_redirect(:user, user)
    else
      session[:omniauth] = omniauth.except('extra')
      redirect_to new_user_registration_url
    end
  end
  end

  # PATCH/PUT /authentications/1
  # PATCH/PUT /authentications/1.json
  def update
    respond_to do |format|
      if @authentication.update(authentication_params)
        format.html { redirect_to @authentication, notice: 'Authentication was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @authentication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authentications/1
  # DELETE /authentications/1.json
  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_authentication
      @authentication = Authentication.find(params[:id])
    end
    
    def image_set(user,omniauth)
      if omniauth.info.image.present? && omniauth.provider != 'linkedin' && user.avatar.blank?
  avatar_url = process_uri(omniauth.info.image+'?type=large')
  user.update_attribute(:avatar, URI.parse(avatar_url))
      end
    end

    def update_omniauth(user,omniauth)
      if omniauth.info.name.present?
        user.update_attribute(:name,omniauth.info.name)
      end
      if omniauth.extra.raw_info.birthday.present?
  date=Date.strptime(omniauth.extra.raw_info.birthday,'%m/%d/%Y')
        user.update_attribute(:date_of_birth,date)
      end
    end

    def process_uri(uri)
      require 'open-uri'
      require 'open_uri_redirections'
      open(uri, :allow_redirections => :safe) do |r|
  r.base_uri.to_s
      end
    end
 
    # Never trust parameters from the scary internet, only allow the white list through.
    def authentication_params
      params.require(:authentication).permit(:user_id, :provider, :uids)
    end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/views/authentications/_form.html.erb
<%= simple_form_for(@authentication) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.input :provider %>
    <%= f.input :uid %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/authentications/edit.html.erb
<h1>Editing Authentication</h1>

<%= render 'form' %>

<%= link_to 'Show', @authentication %> |
<%= link_to 'Back', authentications_path %>

app/views/authentications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Authentications</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Provider</th>
      <th>Uid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authentications.each do |authentication| %>
      <tr>
        <td><%= authentication.user %></td>
        <td><%= authentication.provider %></td>
        <td><%= authentication.uid %></td>
        <td><%= link_to 'Show', authentication %></td>
        <td><%= link_to 'Edit', edit_authentication_path(authentication) %></td>
        <td><%= link_to 'Destroy', authentication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Authentication', new_authentication_path %>

app/views/authentications/new.html.erb
<h1>New Authentication</h1>

<%= render 'form' %>

<%= link_to 'Back', authentications_path %>

app/views/authentications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @authentication.user %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @authentication.provider %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @authentication.uid %>
</p>

<%= link_to 'Edit', edit_authentication_path(@authentication) %> |
<%= link_to 'Back', authentications_path %>